services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis:6379
      REDIS_PASSWORD:
      RATE_LIMIT_IP: 3
      RATE_LIMIT_TOKEN: 5
      BLOCKED_TIME: 60s
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3